server:
  port: 8080
  forward-headers-strategy: native
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.session.SessionAutoConfiguration
  application:
    name: back
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
management:
  endpoints:
    web:
      base-path: /actuator            # 기본값이지만 명시
      exposure:
        include: health,info          # 필요시 metrics 등 추가
  endpoint:
    health:
      probes:
        enabled: true                 # /actuator/health/{liveness,readiness} 활성화
      show-details: never             # 프로브 용도면 never 권장(민감정보 차단)
  custom:
    dev:
      cookieDomain: localhost
      frontUrl: http://${custom.dev.cookieDomain}:3000
      backUrl: http://${custom.dev.cookieDomain}:${server.port}
    prod:
      cookieDomain: nutree.noredsun.com
      frontUrl: https://www.${custom.prod.cookieDomain}
      backUrl: https://api.${custom.prod.cookieDomain}
    site:
      cookieDomain: "${custom.dev.cookieDomain}"
      frontUrl: "${custom.dev.frontUrl}"
      backUrl: "${custom.dev.backUrl}"
      name: nutree
custom:
  jwt:
    secretKey: "7f11da8036a2af0c57fe894d1a7efd0bca9d86b58ad93fe11e7a52960044e82a"
  accessToken:
    expirationSeconds: "#{60*20}"