spring:
  application:
    name: back
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
management:
  endpoints:
    web:
      base-path: /actuator            # 기본값이지만 명시
      exposure:
        include: health,info          # 필요시 metrics 등 추가
  endpoint:
    health:
      probes:
        enabled: true                 # /actuator/health/{liveness,readiness} 활성화
      show-details: never             # 프로브 용도면 never 권장(민감정보 차단)